blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/k6w/seekr/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/k6w/seekr/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📖 Documentation
    url: https://github.com/k6w/seekr#readme
    about: Read the project documentation
